routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Public routes (do not require authentication)
 */
Route::get('/', 'PageController@index')->name('page.index');
Route::get('/product/{slug}', 'PageController@product')->name('page.product');
Route::post('/rfq-details', 'PageController@rfqDetails')->name('post.rfq-details');

/**
 * Auth routes (public)
 */
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/**
 * Admin routes (require authentication)
 */
Route::get('/admin', 'HomeController@index');
Route::get('/admin/requests/download-attachment', 'RequestController@downloadAttachment')->name('request.downloadAttachment');
Route::resource('requests', 'RequestController');
Route::resource('users', 'UserController');
Route::resource('sliders', 'SliderController');
Route::resource('products', 'ProductController');
Route::resource('testimonials', 'TestimonialController');
Route::resource('whyus', 'WhyUsController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ env('APP_NAME') }}</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <link rel="shortcut icon" href="{{ asset('flatpack/images/favicon.ico') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.11/css/AdminLTE.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.11/css/skins/_all-skins.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css">

    <!-- Pixicon -->
    <link rel="stylesheet" href="{{ asset('flatpack/css/pixicon.css') }}">

    @php ($avatar = asset('flatpack/images/anonymous.png'))

    @yield('css')
</head>

<body class="skin-blue sidebar-mini">
<div class="wrapper">
    <!-- Main Header -->
    <header class="main-header">

        <!-- Logo -->
        <a href="#" class="logo">
            <b>{{ env('APP_NAME') }}</b>
        </a>

        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- User Account Menu -->
                    <li class="dropdown user user-menu">
                        <!-- Menu Toggle Button -->
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <!-- The user image in the navbar-->
                            <img src="{{ $avatar }}" class="user-image" alt="User Image"/>
                            <!-- hidden-xs hides the username on small devices so only the image appears. -->
                            <span class="hidden-xs">{!! Auth::user()->name !!}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- The user image in the menu -->
                            <li class="user-header">
                                <img src="{{ $avatar }}" class="img-circle" alt="User Image"/>
                                <p>
                                    {!! Auth::user()->name !!}
                                    <small>Member since {!! Auth::user()->created_at->format('M. Y') !!}</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">Profile</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{!! url('/logout') !!}" class="btn btn-default btn-flat"
                                       onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                        Sign out
                                    </a>
                                    <form id="logout-form" action="{{ url('/logout') }}" method="POST"
                                          style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <!-- Left side column. contains the logo and sidebar -->
@include('layouts.sidebar')
<!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        @yield('content')
    </div>

    <!-- Main Footer -->
    <footer class="main-footer" style="max-height: 100px;text-align: center">
        <strong>Copyright © 2016 <a href="http://infyom.com" target="_blank">InfyOm Technologies</a>.</strong> All rights reserved.
    </footer>

</div>


<!-- jQuery 3.1.1 -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>

<!-- AdminLTE App -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.11/js/app.min.js"></script>

@yield('scripts')
</body>
</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/menu.blade.php
<li class="{{ Request::is('products*') ? 'active' : '' }}">
    <a href="{!! route('products.index') !!}"><i class="fa fa-edit"></i><span>Products</span></a>
</li>

<li class="{{ Request::is('requests*') ? 'active' : '' }}">
    <a href="{!! route('requests.index') !!}"><i class="fa fa-edit"></i><span>Requests</span></a>
</li>

<li class="{{ Request::is('sliders*') ? 'active' : '' }}">
    <a href="{!! route('sliders.index') !!}"><i class="fa fa-edit"></i><span>Sliders</span></a>
</li>

<li class="{{ Request::is('testimonials*') ? 'active' : '' }}">
    <a href="{!! route('testimonials.index') !!}"><i class="fa fa-edit"></i><span>Testimonials</span></a>
</li>

<li class="{{ Request::is('users*') ? 'active' : '' }}">
    <a href="{!! route('users.index') !!}"><i class="fa fa-edit"></i><span>Users</span></a>
</li>
<li class="{{ Request::is('whyus*') ? 'active' : '' }}">
    <a href="{!! route('whyus.index') !!}"><i class="fa fa-edit"></i><span>Why Us</span></a>
</li>

resources/views/layouts/public.blade.php
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="{{ config('app.locale') }}"> <!--<![endif]-->
<head>
    <!-- Basic Page Needs
    ================================================== -->
    <meta charset="utf-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ env('APP_NAME') }}</title>
    <meta name="description" content="{{ env('APP_DESC') }}">
    <meta name="keywords" content="{{ env('APP_KEYWORDS') }}">
    <meta name="author" content="{{ env('APP_URL') }}">

    <!-- Mobile Specific Metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="x-ua-compatible" content="IE=9">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <!--headerIncludes-->
    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{{ asset('flatpack/css/font-awesome.css') }}">
    <link rel="stylesheet" href="{{ asset('flatpack/css/menu.css') }}">
    <link rel="stylesheet" href="{{ asset('flatpack/css/flat-ui-slider.css') }}">
    <link rel="stylesheet" href="{{ asset('flatpack/css/base.css') }}">
    <link rel="stylesheet" href="{{ asset('flatpack/css/skeleton.css') }}">
    <link rel="stylesheet" href="{{ asset('flatpack/css/landings.css') }}">
    <link rel="stylesheet" href="{{ asset('flatpack/css/main.css') }}">
    <link rel="stylesheet" href="{{ asset('flatpack/css/landings_layouts.css') }}">
    <link rel="stylesheet" href="{{ asset('flatpack/css/box.css') }}">
    <link rel="stylesheet" href="{{ asset('flatpack/css/pixicon.css') }}">
    <link rel="stylesheet" href="{{ asset('flatpack/css/animations.min.css') }}">
    <link rel="stylesheet" href="{{ asset('auto-complete/auto-complete.css') }}">

    <!--[if lt IE 9]>
    <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!-- Favicons
    ================================================== -->
    <link rel="shortcut icon" href="{{ asset('flatpack/images/favicon.ico') }}">
    <link rel="apple-touch-icon" href="{{ asset('flatpack/images/apple-touch-icon.png') }}">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ asset('flatpack/images/apple-touch-icon-72x72.png') }}">
    <link rel="apple-touch-icon" sizes="114x114" href="{{ asset('flatpack/images/apple-touch-icon-114x114.png') }}">

    @yield('styles')
</head>
<body>

    <div id="page" class="page">
        <div class="header_nav_1 dark inter_3_bg pix_builder_bg" id="section_intro_3">
            <div class="header_style">
                <div class="container">
                    <div class="sixteen columns firas2">
                        <nav role="navigation" class="navbar navbar-white navbar-embossed navbar-lg pix_nav_1">
                            <div class="containerss">
                                <div class="navbar-header">
                                    <button data-target="#navbar-collapse-02" data-toggle="collapse" class="navbar-toggle" type="button">
                                        <span class="sr-only">Toggle navigation</span>
                                    </button>
                                    <div class="brand"><a href="{{ route('page.index') }}">{{ env('APP_NAME') }}</a></div>
                                </div>
                                <div id="navbar-collapse-02" class="collapse navbar-collapse">
                                    <ul class="nav navbar-nav navbar-right">
                                        <li class="active propClone"><a href="{{ route('page.index') }}">Home</a></li>
                                        <li class="propClone dropdown">
                                            <a class="dropdown-toggle" href="javascript:">Product</a>
                                            <ul class="dropdown-menu">
                                                @foreach ($products as $prod)
                                                <li><a href="{{ route('page.index') }}#{{ $prod->slug }}">{{ $prod->name }}</a></li>
                                                @endforeach
                                            </ul>
                                        </li>
                                        <li class="propClone"><a href="{{ route('page.index') }}#why-us">Why Us</a></li>
                                        <li class="propClone"><a href="{{ route('page.index') }}#rfq">RFQ</a></li>
                                    </ul>
                                </div><!-- /.navbar-collapse -->
                            </div><!-- /.container -->
                        </nav>
                    </div>
                </div><!-- container -->
            </div>

            @yield('header')

        </div>

        @yield('content')

        <div class="pixfort_party_15" id="section_party_4">
            <div class="foot_st pix_builder_bg" style="outline: none; cursor: default;">
                <div class="container">
                    <div class="sixteen columns">
                        <span class="editContent">
                            <span class="pix_text" style="outline: none; cursor: default;">
                                <span class="rights_st"> All rights reserved Copyright © 2017 {{ env('APP_NAME') }}</span>
                            </span>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>

<!-- JavaScript
================================================== -->
<script src="{{ asset('flatpack/js/jquery-1.8.3.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('flatpack/js/jquery.easing.1.3.js') }}" type="text/javascript"></script>
<script src="{{ asset('flatpack/js/jquery.common.min.js') }}" type="text/javascript" ></script>
<script src="{{ asset('flatpack/js/ticker.js') }}" type="text/javascript"></script>
<script src="{{ asset('flatpack/js/smoothscroll.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('flatpack/js/appear.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('flatpack/js/jquery.ui.touch-punch.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('flatpack/js/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('flatpack/js/bootstrap-switch.js') }}" type="text/javascript"></script>
<script src="{{ asset('flatpack/js/custom1.js') }}" type="text/javascript"></script>
<script src="{{ asset('flatpack/js/appear.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('flatpack/js/animations.js') }}" type="text/javascript"></script>

<script src="{{ asset('flatpack/js/public.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/jquery.smooth-scroll.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('auto-complete/auto-complete.min.js') }}" type="text/javascript"></script>

@yield('scripts')

</body>
</html>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ $avatar }}" class="img-circle" alt="User Image"/>
            </div>
            <div class="pull-left info">
                @if (Auth::guest())
                <p>InfyOm</p>
                @else
                    <p>{{ Auth::user()->name}}</p>
                @endif
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
          <span class="input-group-btn">
            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
            </div>
        </form>
        <!-- Sidebar Menu -->

        <ul class="sidebar-menu">
            @include('layouts.menu')
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>